---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars:
    my_home: "{{ lookup('env','HOME') }}"
    rvm1_install_path: "{{ my_home }}/.rvm"
    rvm1_install_flags: '--auto-dotfiles --user-install'
    rvm1_user: "{{ lookup('env','USER') }}"

  roles:
    - role: common
    - role: rvm_io.rvm1-ruby
    - role: bonusbox

  tasks:
    - name: symlink postgresql
      file:
        src: /usr/local/opt/postgresql/homebrew.mxcl.postgresql.plist
        dest: "{{ my_home }}/Library/LaunchAgents/homebrew.mxcl.postgresql.plist"
        state: link
      tags: postgres

    - name: start postgres
      shell: "launchctl load {{ my_home }}/Library/LaunchAgents/homebrew.mxcl.postgresql.plist"

    - name: install my homebrew setup
      homebrew:
        name: "{{ item }}"
        state: latest
      tags: brew
      with_items:
        - emacs
        - reattach-to-user-namespace

    - name: "download my emacs git repository to .emacs.d"
      git:
        repo: "git@github.com:riethmayer/emacs.git"
        dest: "{{ my_home }}/.emacs.d"
        accept_hostkey: yes
      tags: emacs

    - name: setup src directory
      file:
        path: "{{ my_home }}/src"
        state: directory
      tags: bash

    - name: setup github directory
      file:
        path: "{{ my_home }}/github"
        state: directory
      tags: bash

    - name: setup bonusbox directory
      file:
        path: "{{ my_home }}/bonusbox/projects"
        state: directory
      tags: bash

    - name: download dotfiles
      git:
        repo: "git@github.com:riethmayer/dotfiles.git"
        dest: "{{ my_home }}/src/dotfiles"
        accept_hostkey: yes
      tags: bash

    - name: symlink flat files
      file:
        src: "{{ my_home }}/src/dotfiles/{{ item }}"
        dest: "{{ my_home }}/.{{ item }}"
        state: link
      with_items:
        - gemrc
        - gitconfig
        - tmux.conf
      tags: bash

    - name: symlink bash_profile
      file:
        src: "{{ my_home }}/src/dotfiles/bash/{{ item }}"
        dest: "{{ my_home }}/.{{ item }}"
        state: link
      with_items:
        - bash_profile
      tags: bash

    - name: symlink bin directory
      file:
        src: "{{ my_home }}/src/dotfiles/bin"
        dest: "{{ my_home }}/bin"
        state: link
      tags: bash

    - name: symlink gls to ls
      file:
        src: /usr/local/bin/gls
        dest: /usr/local/bin/ls
        state: link
      tags: bash

    - name: download my secrets
      git:
        repo: "git@bitbucket.com:riethmayer/secret.git"
        dest: "{{ my_home }}/src/secret"
        accept_hostkey: yes
      tags: bash

    - name: install binaries
      homebrew_cask:
        name: "{{ item }}"
        state: present
      tags: binaries
      with_items:
        - dropbox
        - evernote
        - firefox
        - flash-player
        - flowdock
        - google-chrome
        - iterm2
        - opera
        - screenhero
        - silverlight
        - sketch
        - skype
        - spotify
        - vagrant
        - vlc
# - virtualbox doesn't work at the moment, nvm

    - name: Install hub
      homebrew:
        name: hub
        state: latest
      tags: homebrew

    - name: Install mactex
      homebrew_cask:
        name: mactex
        state: present
      tags: latex
