---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars:
    my_home: "{{ lookup('env','HOME') }}"
    rvm1_install_path: "{{ my_home }}/.rvm"
    rvm1_install_flags: '--auto-dotfiles --user-install'
    rvm1_user: "{{ lookup('env','USER') }}"

  roles:
    - role: common
    - role: rvm_io.rvm1-ruby

  tasks:
    - name: setup src directory
      file:
        path: "{{ my_home }}/src"
        state: directory
      tags: bash

    - name: setup github directory
      file:
        path: "{{ my_home }}/github"
        state: directory
      tags: bash

    - name: download dotfiles
      git:
        repo: "git@github.com:riethmayer/dotfiles.git"
        dest: "{{ my_home }}/src/dotfiles"
        accept_hostkey: yes
      tags: bash

    - name: symlink flat files
      file:
        src: "{{ my_home }}/src/dotfiles/{{ item }}"
        dest: "{{ my_home }}/.{{ item }}"
        state: link
      with_items:
        - eslintrc
        - gemrc
        - gitconfig
        - jsbeautifyrc
        - tmux.conf
      tags: bash

    - name: symlink bash_profile
      file:
        src: "{{ my_home }}/src/dotfiles/bash/{{ item }}"
        dest: "{{ my_home }}/.{{ item }}"
        state: link
      with_items:
        - bash_profile
      tags: bash

    - name: symlink bin directory
      file:
        src: "{{ my_home }}/src/dotfiles/bin"
        dest: "{{ my_home }}/bin"
        state: link
      tags: bash

    - name: symlink gls to ls
      file:
        src: /usr/local/bin/gls
        dest: /usr/local/bin/ls
        state: link
      tags: bash

    - name: download my secrets
      git:
        repo: "git@github.com:riethmayer/secret.git"
        dest: "{{ my_home }}/src/secret"
        accept_hostkey: yes
      tags: bash

    - name: install binaries
      homebrew_cask:
        name: "{{ item }}"
        state: present
      tags: binaries
      with_items:
        - firefox
        - flash-player
        - google-chrome
        - opera
        - vlc

    - name: install basic command line tools
      homebrew:
        name: "{{ item.name }}"
        state: latest
      tags: brewd
      with_items:
        - { name: ack }
        - { name: emacs }
        - { name: git }
        - { name: mercurial }
        - { name: hub }
        - { name: jq }
        - { name: lua }
        - { name: markdown }
        - { name: reattach-to-user-namespace }
        - { name: the_silver_searcher }
        - { name: watch }
        - { name: wget }
        - { name: tmux }
        - { name: tree }
        - { name: bash }
        - { name: cairo }
        - { name: colordiff }
        - { name: coreutils }
        - { name: direnv }
        # - { name: r } installation takes forever
    - name: js tools
      homebrew:
        name: "{{ item.name }}"
        state: latest
      tags: brew
      with_items:
        - { name: node }
        - { name: yarn }

    - name: install make tools
      homebrew:
        name: "{{ item.name }}"
        state: latest
      tags: brew
      with_items:
        - { name: autoconf }
        - { name: automake }
        - { name: gcc }
        - { name: gdbm }
        - { name: libevent }
        - { name: libffi }
        - { name: libgpg-error }
        - { name: libidn }
        - { name: libksba }
        - { name: libmpc }
        - { name: libpng }
        - { name: libtiff }
        - { name: libtool }
        - { name: libyaml }
        - { name: llvm }
        - { name: openssl }
        - { name: openssl@1.1 }
        - { name: qt }
        - { name: readline }

    - name: install elixir development tools
      homebrew:
        name: "{{ item.name }}"
        state: latest
      tags: brew
      with_items:
        - { name: elixir }
        - { name: erlang }

    - name: install generic development tools
      tags: brew
      homebrew:
        name: "{{ item.name }}"
        state: latest
      with_items:
        - { name: chromedriver }
        - { name: cloc }
        - { name: fontconfig }
        - { name: freetype }
        - { name: gettext }
        - { name: glib }
        - { name: gmp }
        - { name: gnupg }
        - { name: icu4c }
        - { name: isl }

    - name: install image tools
      homebrew:
        name: "{{ item.name }}"
        state: latest
      tags: brew
      with_items:
        - { name: gd }
        - { name: gnuplot }
        - { name: graphviz }
        - { name: imagemagick }
        - { name: jpeg }
        
    - name: install devops tools
      homebrew:
        name: "{{ item.name }}"
        state: latest
      tags: brew
      with_items:
        - { name: awscli }
        - { name: heroku }
        - { name: heroku-toolbelt }
        - { name: kubernetes-helm }

