---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars:
    my_home: "{{ lookup('env','HOME') }}"
    rvm1_install_path: "{{ my_home }}/.rvm"
    rvm1_install_flags: '--auto-dotfiles --user-install'
    rvm1_user: "{{ lookup('env','USER') }}"

  roles:
    - role: common
    - role: rvm_io.rvm1-ruby

  tasks:
    - name: install my homebrew setup
      homebrew:
        name: "{{ item }}"
        state: latest
      tags: brew
      with_items:
        - ack
        - ansible
        - autoconf
        - automake
        - awscli
        - bash
        - cairo
        - chromedriver
        - cloc
        - colordiff
        - coreutils
        - couchdb
        - direnv
        - elasticsearch
        - elixir
        - emacs
        - erlang
        - fontconfig
        - freetype
        - gcc
        - gd
        - gdbm
        - gettext
        - git
        - glib
        - gmp
        - gnupg
        - gnuplot
        - go
        - graphviz
        - heroku
        - heroku-toolbelt
        - hub
        - icu4c
        - imagemagick
        - isl
        - jpeg
        - jq
        - kubernetes-helm
        - leiningen
        - libevent
        - libffi
        - libgpg-error
        - libidn
        - libksba
        - libmpc
        - libpng
        - libtiff
        - libtool
        - libyaml
        - llvm
        - lua
        - markdown
        - mercurial
        - mpfr
        - mysql
        - nmap
        - node
        - nspr
        - oniguruma
        - openssl
        - openssl@1.1
        - pcre
        - perl
        - pixman
        - pkg-config
        - postgresql
        - pstree
        - python
        - qt
        - r
        - rabbitmq
        - rbenv
        - readline
        - reattach-to-user-namespace
        - redis
        - ruby
        - ruby-build
        - selenium-server-standalone
        - spidermonkey
        - sqlite
        - the_silver_searcher
        - tmux
        - tree
        - unixodbc
        - vim
        - watch
        - watchman
        - webp
        - wget
        - wxmac
        - xz
        - yarn
        - zsh
        - zsh-completions

    - name: install spacemacs
      git:
        repo: "git@github.com:syl20bnr/spacemacs.git"
        dest: "{{ my_home }}/.emacs.d"
        accept_hostkey: yes

    - name: setup src directory
      file:
        path: "{{ my_home }}/src"
        state: directory
      tags: bash

    - name: setup github directory
      file:
        path: "{{ my_home }}/github"
        state: directory
      tags: bash

    - name: download dotfiles
      git:
        repo: "git@github.com:riethmayer/dotfiles.git"
        dest: "{{ my_home }}/src/dotfiles"
        accept_hostkey: yes
      tags: bash

    - name: symlink flat files
      file:
        src: "{{ my_home }}/src/dotfiles/{{ item }}"
        dest: "{{ my_home }}/.{{ item }}"
        state: link
      with_items:
        - gemrc
        - gitconfig
        - tmux.conf
        - spacemacs
      tags: bash

    - name: symlink bash_profile
      file:
        src: "{{ my_home }}/src/dotfiles/bash/{{ item }}"
        dest: "{{ my_home }}/.{{ item }}"
        state: link
      with_items:
        - bash_profile
      tags: bash

    - name: symlink bin directory
      file:
        src: "{{ my_home }}/src/dotfiles/bin"
        dest: "{{ my_home }}/bin"
        state: link
      tags: bash

    - name: symlink gls to ls
      file:
        src: /usr/local/bin/gls
        dest: /usr/local/bin/ls
        state: link
      tags: bash

    - name: download my secrets
      git:
        repo: "git@github.com:riethmayer/secret.git"
        dest: "{{ my_home }}/src/secret"
        accept_hostkey: yes
      tags: bash

    - name: install binaries
      homebrew_cask:
        name: "{{ item }}"
        state: present
      tags: binaries
      with_items:
        - firefox
        - flash-player
        - google-chrome
        - opera
        - vlc
